### ISSUE TITLE
开启赛季时报错

### ISSUE THREAD

**Issue by sapphire159** [ssttkkl/nonebot-plugin-mahjong-scoreboard#15]
输入命令开启赛季，根据提示输入y后报错。

12-02 21:02:58 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mahjong_scoreboard.controller.season_manage, lineno=264) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\ssttkkl_nonebot_utils\errors\error_handler.py", line 88, in run_excepting
    await coro
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\ssttkkl_nonebot_utils\interceptor\handle_error.py", line 24, in receive_error_message
    await matcher.finish()
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 571, in finish
    raise FinishedException
nonebot.exception.FinishedException: FinishedException()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\ssttkkl_nonebot_utils\interceptor\handle_error.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\season_manage.py", line 300, in start_season_end
    await season_service.start_season(matcher.state["season"].id, operator.id)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\service\season_service.py", line 74, in start_season
    await _ensure_permission(season, operator_user_id)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\service\season_service.py", line 16, in _ensure_permission
    if not await is_group_admin(operator_user_id, season.group_id):
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\service\group_service.py", line 33, in is_group_admin
    return await platform_func(bot).is_group_admin(session)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\ssttkkl_nonebot_utils\platform\func_manager.py", line 19, in __getattr__
    raise UnsupportedBotError()
ssttkkl_nonebot_utils.platform.func_manager.UnsupportedBotError

**Comment by ssttkkl** [comment]
什么平台？什么适配器？
________________________________
From: sapphire159 ***@***.***>
Sent: Saturday, December 2, 2023 9:12:16 PM
To: bot-ssttkkl/nonebot-plugin-mahjong-scoreboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bot-ssttkkl/nonebot-plugin-mahjong-scoreboard] 开启赛季时报错 (Issue #15)


输入命令开启赛季，根据提示输入y后报错。

12-02 21:02:58 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mahjong_scoreboard.controller.season_manage, lineno=264) failed.
Traceback (most recent call last):
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\ssttkkl_nonebot_utils\errors\error_handler.py", line 88, in run_excepting
await coro
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\ssttkkl_nonebot_utils\interceptor\handle_error.py", line 24, in receive_error_message
await matcher.finish()
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 571, in finish
raise FinishedException
nonebot.exception.FinishedException: FinishedException()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 25, in
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot_init_.py", line 331, in run
get_driver().run(*args, **kwargs)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
uvicorn.run(
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\uvicorn\main.py", line 587, in run
server.run()
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\uvicorn\server.py", line 61, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
self.run_forever()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
self._run_once()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
handle._run()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
await _run_matcher(

File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\message.py", line 428, in run_matcher
await matcher.run(bot, event, state, stack, dependency_cache)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
await self.simple_run(bot, event, state, stack, dependency_cache)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
await handler(
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot\dependencies_init.py", line 113, in call
return await cast(Callable[..., Awaitable[R]], self.call)(**values)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\ssttkkl_nonebot_utils\interceptor\handle_error.py", line 27, in wrapper
return await func(*args, **kwargs)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\season_manage.py", line 300, in start_season_end
await season_service.start_season(matcher.state["season"].id, operator.id)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\service\season_service.py", line 74, in start_season
await _ensure_permission(season, operator_user_id)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\service\season_service.py", line 16, in _ensure_permission
if not await is_group_admin(operator_user_id, season.group_id):
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\service\group_service.py", line 33, in is_group_admin
return await platform_func(bot).is_group_admin(session)
File "C:\Users\Administrator\QQ-bot1.venv\lib\site-packages\ssttkkl_nonebot_utils\platform\func_manager.py", line 19, in getattr
raise UnsupportedBotError()
ssttkkl_nonebot_utils.platform.func_manager.UnsupportedBotError

―

**Comment by sapphire159** [comment]
是win10 22H2。不过我已经解决了，是因为风控报错导致的。现在我有另一个问题。那就是如何完全重置数据，因为有些测试数据影响群内的个人对局数据了

**Comment by sapphire159** [comment]
windows22h2 后端是gocqhttp 。我在注释掉这部分需求校验管理员的程序后可以用了。另外就是这个测试数据影响个人数据了，能不能删除的呢，我把赛季结束之后，赛季就没法删除了。

**Comment by sapphire159** [comment]
机器人是nonebot2.1.2，目前是把_ensure_permission这些都注释掉了在用。

**Comment by ssttkkl** [comment]
不支持删除，建议把库拖了（
________________________________

**Comment by sapphire159** [comment]
那个旧对局我把代码里的赛季状态的校验都注释了，强行把赛季重开了撤销的。现在主要问题还是这个_ensure_permission权限校验报错，导致现在运行的时候都是开放式的。用到是能用。

**Comment by ssttkkl** [comment]
排查到确实是有个地方写错了，执行下`pip install ssttkkl-nonebot-utils==0.1.19`再试试

**Comment by sapphire159** [comment]
确实没报错了，但是有没有限制权限还是待测试。另外我看这个对局编号设计，每天只有100场的空间么，虽然实际应该是够了，但是总感觉不是很有安全感呢。

**Comment by ssttkkl** [comment]
超过100场会变成9位数，以此类推。不过实际上没见过这个场景（
________________________________
