### ISSUE TITLE
貌似Pydantic v2没有适配好

### ISSUE THREAD

**Issue by ChangMenQAQ** [ssttkkl/nonebot-plugin-mahjong-scoreboard#17]
10-26 10:37:43 [ERROR] nonebot | Failed to import "nonebot_plugin_mahjong_scoreboard"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\YPBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\YPBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\YPBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\YPBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\YPBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\Administrator\Desktop\YPBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\__init__.py", line 17, in <module>
    from .controller import game_record, game_query, game_export, season_query, season_manage, season_user_point_query, \
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\controller\__init__.py", line 1, in <module>
    from . import game_export
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\controller\game_export.py", line 9, in <module>
    from .mapper.game_csv_mapper import write_games_csv
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\controller\mapper\__init__.py", line 7, in <module>
    from ...model import PlayerAndWind, GameState, SeasonState, Wind
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\model\__init__.py", line 1, in <module>
    from .business import *
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\model\business.py", line 153, in <module>
    class Game(BaseModel):
  File "C:\Users\Administrator\Desktop\YPBot\YPBot\plugins\nonebot_plugin_mahjong_scoreboard\model\business.py", line 161, in Game
    records: conlist(GameRecord, max_items=4)
TypeError: conlist() got an unexpected keyword argument 'max_items'

**Comment by ssttkkl** [comment]
草
