### ISSUE TITLE
question

### ISSUE THREAD

**Issue by MINTDUCKK** [ssttkkl/nonebot-plugin-mahjong-scoreboard#9]
作者大大你好 我在nonebot上安装scoreboard后出现了如下问题

内部错误：<class 'sqlalchemy.exc.IntegrityError'>(sqlite3.IntegrityError) NOT NULL constraint failed: groups.prev_game_code_base
[SQL: INSERT INTO groups (binding_qq, running_season_id, prev_game_code_base, prev_game_code_identifier) VALUES (?, ?, ?, ?)]
[parameters: (568691329, None, None, None)]

请问这是否是我有什么参数未配置正确呢？

**Comment by ssttkkl** [comment]
这是旧版本的bug，目前插件正在重构中，可以尝试安装0.4.0a1版本

**Comment by MINTDUCKK** [comment]
抱歉 我最新只找到了0.3.1版本 请问哪里有0.4.0a1版本呢

**Comment by ssttkkl** [comment]
pip install nonebot-plugin-mahjong-scoreboard==0.4.0a2

**Comment by ssttkkl** [comment]
0.4.0版本已发布，欢迎尝试

**Comment by MINTDUCKK** [comment]
非常感谢 之前由于使用清华源所以无法找到最新版本，更换阿里源后我成功更新了新版本，但是加载过程中报错如下：
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "G:\ANACONDA3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\__init__.py", line 68, in <module>
    from . import controller
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\__init__.py", line 1, in <module>
    from . import game_export
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\game_export.py", line 10, in <module>
    from .utils.dep import GroupDep, SeasonFromUnaryArgOrRunningSeason
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\utils\dep.py", line 11, in <module>
    from .message import split_message
  File "G:\ANACONDA3\MintDuck\.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\utils\message.py", line 3, in <module>
    from nonebot.adapters.qqguild import Message, MessageSegment
**### ModuleNotFoundError: No module named 'nonebot.adapters.qqguild'**

qqguild好像是qq频道的插件？

**Comment by MINTDUCKK** [comment]
安装了雷神工业插件后此报错解决，已可以正常使用本插件，谢谢！！

**Comment by ssttkkl** [comment]
> 非常感谢 之前由于使用清华源所以无法找到最新版本，更换阿里源后我成功更新了新版本，但是加载过程中报错如下： Traceback (most recent call last): File "", line 14, in File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins return manager.load_all_plugins() File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins return set( File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> 
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
> > module = importlib.import_module(name)
> > File "G:\ANACONDA3\lib\importlib__init__.py", line 126, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1050, in _gcd_import
> > File "", line 1027, in _find_and_load
> > File "", line 1006, in _find_and_load_unlocked
> > File "", line 688, in _load_unlocked
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
> > super().exec_module(module)
> > File "", line 883, in exec_module
> > File "", line 241, in _call_with_frames_removed
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard__init__.py", line 68, in 
> > from . import controller
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller__init__.py", line 1, in 
> > from . import game_export
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\game_export.py", line 10, in 
> > from .utils.dep import GroupDep, SeasonFromUnaryArgOrRunningSeason
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\utils\dep.py", line 11, in 
> > from .message import split_message
> > File "G:\ANACONDA3\MintDuck.venv\lib\site-packages\nonebot_plugin_mahjong_scoreboard\controller\utils\message.py", line 3, in 
> > from nonebot.adapters.qqguild import Message, MessageSegment
> > **### ModuleNotFoundError: No module named 'nonebot.adapters.qqguild'**
> 
> qqguild好像是qq频道的插件？

是我的bug，已修复
